server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 本地数据库
#    url: jdbc:mysql://localhost:3306/recipe_share?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # docker配置
#    url: jdbc:mysql://mysql-container:3306/recipe_share?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 本地开发连云服数据库
    url: jdbc:mysql://8.163.57.20:3306/recipe_share?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#    password: root
    password: 123456
  ai:
    openai:
      #千万不要将DeepSeekAPIKey提交到github上！！！
      api-key:
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

mybatis-plus:
  type-aliases-package: com.yangyang.whatcanieat.entity
  configuration:
    map-underscore-to-camel-case: true
